Repository GSG-K3/360HMR, pull requests merged in 2020-07, with the labels that each got.

#20 configure the eslint with prettier #19
  .eslintrc.json
  .prettierrc
  client/.eslintrc.json
  client/.prettierrc
  client/package.json
  package.json
Labels: waiting-review

#23 concurrently
  client/package.json
  package.json
Labels: waiting-review

#22 Travis
  .travis.yml
  Readme.md
  package.json
Labels: waiting-review

#25 Database creation
  Readme.md
  server/database/config/db_build.js
  server/database/config/db_build.sql
  server/database/config/db_connection.js
Labels: waiting-review

#40 Adds a pull request template
  .github/pull_request_template.md
Labels: waiting-review

#28 Google signin
  client/.gitignore
  client/package.json
  client/src/App.js
  client/src/components/CommonComponents/SignIn/index.jsx
  client/src/components/CommonComponents/SignIn/style.js
  client/src/components/CommonComponents/SignIn/uiConfig.js
  client/src/components/LayoutComponents/Dashboard/index.jsx
  client/src/components/LayoutComponents/Dashboard/style.js
  client/src/components/LayoutComponents/Home/index.jsx
  client/src/components/LayoutComponents/Home/style.js
  client/src/index.js
  pull_request_template.md
  server/controller/index.js
Labels: waiting-review

#52 Add new employee
  client/package.json
  client/src/App.js
  client/src/components/LayoutComponents/Dashboard/NewMember.jsx
  client/src/components/LayoutComponents/Dashboard/NewMemberStyle.jsx
  package.json
  pull_request_template.md
  server/app.js
  server/controller/employees/addNewEmployee.js
  server/controller/index.js
  server/database/queries/employees/postNewEmployee.js
Labels: waiting-review

#51 Material ui template
  client/package.json
  client/public/index.html
  client/src/components/LayoutComponents/Home/index.jsx
  client/src/theme/MaterialUiTheme.js
Labels: front-end, planning

#35 get employee form
  Readme.md
  client/src/index.js
  pull_request_template.md
  server/controller/forms/getForms.js
  server/controller/index.js
  server/database/config/db_build.sql
  server/database/queries/forms/getForms.js
Labels: waiting-review

#59 History
  .github/pull_request_template.md
  .gitignore
  client/src/App.js
  client/src/components/CommonComponents/LoaderProgress.jsx
  client/src/components/LayoutComponents/Dashboard/History.jsx
  client/src/components/LayoutComponents/Dashboard/HistoryStyle.jsx
  pull_request_template.md
  server/controller/employees/getEmployees.js
  server/controller/index.js
  server/database/queries/employees/getEmployees.js
Labels: waiting-review

#38 Create form backend
  client/package.json
  client/src/App.js
  client/src/components/CommonComponents/Dialog/index.jsx
  client/src/components/LayoutComponents/Dashboard/NewMember.jsx
  client/src/components/LayoutComponents/Form/index.jsx
  client/src/components/LayoutComponents/Form/style.js
  pull_request_template.md
  server/app.js
  server/controller/getQuestions.js
  server/controller/index.js
  server/controller/insertQuestions.js
  server/database/config/db_connection.js
  server/database/queries/getQuestionsQuery.js
  server/database/queries/insertQuestionsQuery.js
Labels: waiting-review

#66 Protect route frontend through auth #65
  client/public/index.html
  client/src/App.js
  client/src/Auth.js
  client/src/PrivateRoute.js
  client/src/components/CommonComponents/SignIn/fire.js
  client/src/components/CommonComponents/SignIn/index.jsx
  client/src/components/LayoutComponents/Dashboard/index.jsx
  client/src/components/LayoutComponents/History/HistoryStyle.jsx
  client/src/components/LayoutComponents/History/index.jsx
  client/src/components/LayoutComponents/Home/index.jsx
  client/src/components/LayoutComponents/NewMember/NewMemberStyle.jsx
  client/src/components/LayoutComponents/NewMember/index.jsx
Labels: waiting-review

#55 Navbar
  client/package.json
  client/public/index.html
  client/src/assets/home.png
  client/src/assets/logo.png
  client/src/components/CommonComponents/NavBar/index.jsx
  client/src/components/CommonComponents/NavBar/style.js
  client/src/components/CommonComponents/Tabs/index.jsx
  client/src/components/CommonComponents/Tabs/style.js
  client/src/components/LayoutComponents/Dashboard/index.jsx
  client/src/components/LayoutComponents/Home/index.jsx
  client/src/theme/MaterialUiTheme.js
Labels: waiting-review

#58 Home page frontend
  client/src/App.css
  client/src/App.js
  client/src/assets/home.png
  client/src/components/CommonComponents/NavBar/index.jsx
  client/src/components/CommonComponents/NavBar/style.js
  client/src/components/CommonComponents/SignIn/firebaseui-styling.global.css
  client/src/components/CommonComponents/SignIn/index.jsx
  client/src/components/CommonComponents/SignIn/style.js
  client/src/components/LayoutComponents/Dashboard/index.jsx
  client/src/components/LayoutComponents/Home/index.jsx
  client/src/components/LayoutComponents/Home/style.js
  client/src/index.js
  client/src/theme/MaterialUiTheme.js
Labels: waiting-review

#63 History front end
  client/src/components/LayoutComponents/History/HistoryStyle.jsx
  client/src/components/LayoutComponents/History/index.jsx
  client/src/components/LayoutComponents/NewMember/NewMemberStyle.jsx
  client/src/components/LayoutComponents/NewMember/index.jsx
  client/src/img/addEmp.png
  server/database/queries/employees/getEmployees.js
Labels: waiting-review

#68 History details
  .github/pull_request_template.md
  client/src/App.js
  client/src/components/LayoutComponents/History/HistoryStyle.jsx
  client/src/components/LayoutComponents/HistoryDetails/index.jsx
  client/src/components/LayoutComponents/TheResult/index.jsx
  pull_request_template.md
  server/controller/employees/getEmpById.js
  server/controller/index.js
  server/database/queries/employees/getEmpById.js
Labels: waiting-review

#69 creating the form frontend with some changes for the backend #45
  client/package.json
  client/src/App.css
  client/src/App.js
  client/src/components/CommonComponents/Header/index.jsx
  client/src/components/CommonComponents/Header/style.js
  client/src/components/CommonComponents/Loader/LoaderProgress.jsx
  client/src/components/CommonComponents/NavBar/style.js
  client/src/components/LayoutComponents/Form/Context.jsx
  client/src/components/LayoutComponents/Form/QuestionsForm/index.jsx
  client/src/components/LayoutComponents/Form/QuestionsForm/style.js
  client/src/components/LayoutComponents/Form/QuestionsList/index.jsx
  client/src/components/LayoutComponents/Form/QuestionsList/style.js
  client/src/components/LayoutComponents/Form/QuestionsTypeSelect/index.jsx
  client/src/components/LayoutComponents/Form/QuestionsTypeSelect/style.js
  client/src/components/LayoutComponents/Form/index.jsx
  client/src/components/LayoutComponents/Form/style.js
  client/src/components/LayoutComponents/History/index.jsx
  client/src/components/LayoutComponents/Home/style.js
  server/controller/getQuestions.js
  server/controller/index.js
  server/controller/questions/getQuestions.js
  server/controller/questions/insertQuestions.js
  server/database/queries/questions/getQuestionsQuery.js
  server/database/queries/questions/insertQuestionsQuery.js
Labels: waiting-review

#72 The result
  client/src/components/LayoutComponents/History/HistoryStyle.jsx
  client/src/components/LayoutComponents/HistoryDetails/index.jsx
  client/src/components/LayoutComponents/TheResult/index.jsx
  client/src/components/LayoutComponents/TheResult/theResult.jsx
  pull_request_template.md
  server/controller/forms/getResultForm.js
  server/controller/index.js
  server/database/config/db_build.sql
  server/database/queries/employees/getEmployees.js
  server/database/queries/forms/getResultForm.js
Labels: waiting-review

#70 Share button
  client/package.json
  client/src/components/CommonComponents/sendEmail.js
  package.json
Labels: in-progress

#76 The form
  client/package.json
  client/src/App.css
  client/src/App.js
  client/src/components/CommonComponents/Dialog/index.jsx
  client/src/components/CommonComponents/SignIn/uiConfig.js
  client/src/components/LayoutComponents/Form/FinalForm/index.jsx
  client/src/components/LayoutComponents/Form/index.jsx
  client/src/components/LayoutComponents/NewMember/index.jsx
  client/src/components/LayoutComponents/Selection/Buttons/index.jsx
  client/src/components/LayoutComponents/Selection/index.jsx
Labels: waiting-review
